### PR TITLE
Clean

### LINKED ISSUE #8: bug: replace_publications_in_pub_index_md() behavior changed after cleaning
Cleaning (#6)  unfortunately introduced a bug. The function `replace_publications_in_pub_index_md()` now produces wrong results (content is linked to wrong rec_id and formatting is also not correct, see screenshot for rec_id=1045):
grafik

```
remotes::install_github("kwb-r/kwb.pubs@4ce47443f1812a96e033d5a927a4b307d2d5617b", upgrade = "always")
kwb.pubs::replace_publications_in_pub_index_md(md_paths = pub_md_paths, 
                                               endnote_db_refs = en_refs)
```

Data for bug-fixing: 
- pub_md_paths: https://github.com/KWB-R/pubs/tree/improve-algolia/content/de/publication
- [en_refs.zip](https://github.com/KWB-R/kwb.pubs/files/5145961/en_refs.zip)

Please fix and verify that **publication** stays the same for all records!

### PR DESCRIPTION
**Pull request by hsonne**
Hi @mrustl ,
please have a look at my cleaning, especially at the probable :bug: :bug:

---
This change is [Reviewable](https://reviewable.io/reviews/kwb-r/kwb.pubs/6)

### CODE REVIEW

**Comment by mrustl** [comment]
Thanks @hsonne please fix the following notes:

```
> checking R code for possible problems ... NOTE
  get_pattern: missing arguments not allowed in calls to 'list'
  handle_record_1: no visible binding for global variable 'overwrite'
  handle_record_2: no visible binding for global variable 'overwrite'
  Undefined global functions or variables:
    overwrite
```

**Comment by hsonne** [comment]
@mrustl Everything fixed now. Please verify the results.

**Comment by mrustl** [comment]
Thanks for "blind deep diving" cleaning effort. What is needed in the future will be "tests" to assure that the behavior stays the same.

I am trying to re-create the KWB publications website with https://github.com/KWB-R/pubs/blob/improve-algolia/import_publications_kwb.R, but now get an error: 

https://github.com/KWB-R/pubs/blob/improve-algolia/import_publications_kwb.R#L333

```
remotes::install_github("kwb-r/kwb.pubs@clean", upgrade = "always")

> kwb.pubs::add_projects_to_pub_index_md(endnote_df, col_project = "label")
[1] "rec_id: 72"
Fehler in paste0(pub_dir, rec_id, "/index.md") : 
  Argument "rec_id" fehlt (ohne Standardwert)
```

Data for reproduction
[data_endnote-df_content-publication.zip](https://github.com/KWB-R/kwb.pubs/files/5145504/data_endnote-df_content-publication.zip)

Fixed bug in https://github.com/KWB-R/kwb.pubs/pull/6/commits/4ce47443f1812a96e033d5a927a4b307d2d5617b

**Comment by hsonne** [comment]
Sorry for that. Indeed, krasser Blindflug. Eventuelle bugs sollten aber, so wie dieser, gut zu lokalisieren sein. Almost no duplicated code any more. Almost!

**Review by mrustl — APPROVED** [review]

**Pull request merged**
